# Workflow para o treinamento do modelo.

name: Treinamento e Report

on:
   push:
   workflow_dispatch: 

jobs:
  Setup-e-Executa:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - uses: iterative/setup-dvc@v1
      - name: Dvc Pull
        env:
          GDRIVE_CREDENTIALS_DATA: "${{ secrets.GDRIVE_SECRET }}"
        run: |
          dvc pull --verbose
      - name: Listagem de Arquivos
        run: ls T1/data
      - name: Experimentos
        env:
          GDRIVE_CREDENTIALS_DATA: "${{ secrets.GDRIVE_SECRET }}"
        run: | 
          python -m pip install --upgrade pip
          pip install -r requirements.txt --quiet
          dvc repro
