# Workflow para o treinamento do modelo.

name: Treinamento e Report

on: [push]

jobs:
  config-e-executa:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - uses: iterative/setup-dvc@v1
      - name: Treinamento
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_SECRET }}
        run: |  
          pip install -r requirements.txt
          dvc pull --run-cache
          python T1/data/Untitled-1.py
